import type {Metadata} from "next";
import {Header} from "@/shared/components";
import {ReactNode} from "react";

export const metadata: Metadata = {
    title: "Fullstack Application | Главная",
    description: "Generated by create next app",
};

export default function HomeLayout({children, modal,}: Readonly<{
    children: ReactNode,
    modal: ReactNode;
}>) {
    return (
        <main className={'min-h-screen'}>
            <Header/>
            {modal}
            {children}
        </main>
    );
}
