import type {Metadata} from "next";
import "./globals.css";

import {Nunito} from 'next/font/google';
import {Header} from "@/shared/components";

const nunito = Nunito({
    subsets: ['cyrillic'],
    variable: '--font-nunito',
    weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
    title: "Fullstack Application | Главная",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={nunito.className}>
        {/*<body >*/}
        <main className={'min-h-screen'}>
            <Header/>

            {children}
        </main>
        {/*<main>{children}</main>*/}

        </body>
        </html>
    );
}
