import type {Metadata} from "next";
import {Container, Header} from "@/shared/components";
import {ReactNode} from "react";

export const metadata: Metadata = {
    title: "Fullstack Application | Корзина",
    description: "Generated by create next app",
};

export default function CheckoutLayout({children}: Readonly<{
    children: ReactNode,
}>) {
    return (
        <main className={'min-h-screen bg-[#F4F1EE]'}>
            <Container>
                <Header hasSearch={false} hasCart={false}  className={'border-gray-200'}/>
                {children}
            </Container>
        </main>
    );
}
